- name: "Copy over the keystore"
  copy:
    src: {% raw %}"{{ keystore }}"{% endraw %}
    dest: /home/ubuntu/cert/{% raw %}{{ keystore | basename }}{% endraw %}
    mode: '0440'
    owner: "ubuntu"
    group: "ubuntu"
